- hosts: all
  tasks:
    - name: Updates apt cache
      apt: update_cache=true

    - name: Installs necessary packages
      apt: 
        pkg: ['python3-pip', 'git', 'python-setuptools']
        state: latest

    - name: Deploy our awesome application
      git: repo=https://github.com/anfederico/flaskex.git dest=/Flaskex
      tags: deploy

    - name: Install specified python requirements
      pip:
        requirements: /Flaskex/requirements.txt
    
    - name: run Flaskex
      command: python3 /Flaskex/app.py
      async: True
      poll: 0
